#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HunBeiQuery
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="HunBeiGuanQuDBV2")]
	public partial class HunBeiDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblDevice(tblDevice instance);
    partial void UpdatetblDevice(tblDevice instance);
    partial void DeletetblDevice(tblDevice instance);
    partial void InserttblStation(tblStation instance);
    partial void UpdatetblStation(tblStation instance);
    partial void DeletetblStation(tblStation instance);
    partial void InserttblGroup(tblGroup instance);
    partial void UpdatetblGroup(tblGroup instance);
    partial void DeletetblGroup(tblGroup instance);
    partial void InserttblMeasureSluiceData(tblMeasureSluiceData instance);
    partial void UpdatetblMeasureSluiceData(tblMeasureSluiceData instance);
    partial void DeletetblMeasureSluiceData(tblMeasureSluiceData instance);
    partial void InserttblMeasureSluiceDataLast(tblMeasureSluiceDataLast instance);
    partial void UpdatetblMeasureSluiceDataLast(tblMeasureSluiceDataLast instance);
    partial void DeletetblMeasureSluiceDataLast(tblMeasureSluiceDataLast instance);
    #endregion
		
		public HunBeiDBDataContext() : 
				base(global::HunBeiQuery.Properties.Settings.Default.HunBeiGuanQuDBV2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HunBeiDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HunBeiDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HunBeiDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HunBeiDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblDevice> tblDevice
		{
			get
			{
				return this.GetTable<tblDevice>();
			}
		}
		
		public System.Data.Linq.Table<tblStation> tblStation
		{
			get
			{
				return this.GetTable<tblStation>();
			}
		}
		
		public System.Data.Linq.Table<tblGroup> tblGroup
		{
			get
			{
				return this.GetTable<tblGroup>();
			}
		}
		
		public System.Data.Linq.Table<tblMeasureSluiceData> tblMeasureSluiceData
		{
			get
			{
				return this.GetTable<tblMeasureSluiceData>();
			}
		}
		
		public System.Data.Linq.Table<tblMeasureSluiceDataLast> tblMeasureSluiceDataLast
		{
			get
			{
				return this.GetTable<tblMeasureSluiceDataLast>();
			}
		}
		
		public System.Data.Linq.Table<vMeasureSluiceData> vMeasureSluiceData
		{
			get
			{
				return this.GetTable<vMeasureSluiceData>();
			}
		}
		
		public System.Data.Linq.Table<vMeasureSluiceDataLast> vMeasureSluiceDataLast
		{
			get
			{
				return this.GetTable<vMeasureSluiceDataLast>();
			}
		}
	}
	
	[Table(Name="dbo.tblDevice")]
	public partial class tblDevice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DeviceID;
		
		private System.Nullable<int> _StationID;
		
		private string _Name;
		
		private System.Nullable<int> _Address;
		
		private string _DeviceKind;
		
		private string _DeviceType;
		
		private System.Nullable<bool> _Deleted;
		
		private string _Remark;
		
		private EntitySet<tblMeasureSluiceData> _tblMeasureSluiceData;
		
		private EntityRef<tblStation> _tblStation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDeviceIDChanging(int value);
    partial void OnDeviceIDChanged();
    partial void OnStationIDChanging(System.Nullable<int> value);
    partial void OnStationIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(System.Nullable<int> value);
    partial void OnAddressChanged();
    partial void OnDeviceKindChanging(string value);
    partial void OnDeviceKindChanged();
    partial void OnDeviceTypeChanging(string value);
    partial void OnDeviceTypeChanged();
    partial void OnDeletedChanging(System.Nullable<bool> value);
    partial void OnDeletedChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public tblDevice()
		{
			this._tblMeasureSluiceData = new EntitySet<tblMeasureSluiceData>(new Action<tblMeasureSluiceData>(this.attach_tblMeasureSluiceData), new Action<tblMeasureSluiceData>(this.detach_tblMeasureSluiceData));
			this._tblStation = default(EntityRef<tblStation>);
			OnCreated();
		}
		
		[Column(Storage="_DeviceID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DeviceID
		{
			get
			{
				return this._DeviceID;
			}
			set
			{
				if ((this._DeviceID != value))
				{
					this.OnDeviceIDChanging(value);
					this.SendPropertyChanging();
					this._DeviceID = value;
					this.SendPropertyChanged("DeviceID");
					this.OnDeviceIDChanged();
				}
			}
		}
		
		[Column(Storage="_StationID", DbType="Int")]
		public System.Nullable<int> StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					if (this._tblStation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStationIDChanging(value);
					this.SendPropertyChanging();
					this._StationID = value;
					this.SendPropertyChanged("StationID");
					this.OnStationIDChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_Address", DbType="Int")]
		public System.Nullable<int> Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[Column(Storage="_DeviceKind", DbType="NVarChar(255)")]
		public string DeviceKind
		{
			get
			{
				return this._DeviceKind;
			}
			set
			{
				if ((this._DeviceKind != value))
				{
					this.OnDeviceKindChanging(value);
					this.SendPropertyChanging();
					this._DeviceKind = value;
					this.SendPropertyChanged("DeviceKind");
					this.OnDeviceKindChanged();
				}
			}
		}
		
		[Column(Storage="_DeviceType", DbType="NVarChar(255)")]
		public string DeviceType
		{
			get
			{
				return this._DeviceType;
			}
			set
			{
				if ((this._DeviceType != value))
				{
					this.OnDeviceTypeChanging(value);
					this.SendPropertyChanging();
					this._DeviceType = value;
					this.SendPropertyChanged("DeviceType");
					this.OnDeviceTypeChanged();
				}
			}
		}
		
		[Column(Storage="_Deleted", DbType="Bit")]
		public System.Nullable<bool> Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[Column(Storage="_Remark", DbType="NVarChar(1000)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[Association(Name="tblDevice_tblMeasureSluiceData", Storage="_tblMeasureSluiceData", OtherKey="DeviceID")]
		public EntitySet<tblMeasureSluiceData> tblMeasureSluiceData
		{
			get
			{
				return this._tblMeasureSluiceData;
			}
			set
			{
				this._tblMeasureSluiceData.Assign(value);
			}
		}
		
		[Association(Name="tblStation_tblDevice", Storage="_tblStation", ThisKey="StationID", IsForeignKey=true)]
		public tblStation tblStation
		{
			get
			{
				return this._tblStation.Entity;
			}
			set
			{
				tblStation previousValue = this._tblStation.Entity;
				if (((previousValue != value) 
							|| (this._tblStation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblStation.Entity = null;
						previousValue.tblDevice.Remove(this);
					}
					this._tblStation.Entity = value;
					if ((value != null))
					{
						value.tblDevice.Add(this);
						this._StationID = value.StationID;
					}
					else
					{
						this._StationID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblStation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblMeasureSluiceData(tblMeasureSluiceData entity)
		{
			this.SendPropertyChanging();
			entity.tblDevice = this;
		}
		
		private void detach_tblMeasureSluiceData(tblMeasureSluiceData entity)
		{
			this.SendPropertyChanging();
			entity.tblDevice = null;
		}
	}
	
	[Table(Name="dbo.tblStation")]
	public partial class tblStation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _GroupID;
		
		private int _StationID;
		
		private System.Nullable<bool> _Deleted;
		
		private string _Name;
		
		private string _Remark;
		
		private System.Nullable<int> _CommuniType;
		
		private string _CommuniTypeContent;
		
		private EntitySet<tblDevice> _tblDevice;
		
		private EntityRef<tblGroup> _tblGroup;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroupIDChanging(System.Nullable<int> value);
    partial void OnGroupIDChanged();
    partial void OnStationIDChanging(int value);
    partial void OnStationIDChanged();
    partial void OnDeletedChanging(System.Nullable<bool> value);
    partial void OnDeletedChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnCommuniTypeChanging(System.Nullable<int> value);
    partial void OnCommuniTypeChanged();
    partial void OnCommuniTypeContentChanging(string value);
    partial void OnCommuniTypeContentChanged();
    #endregion
		
		public tblStation()
		{
			this._tblDevice = new EntitySet<tblDevice>(new Action<tblDevice>(this.attach_tblDevice), new Action<tblDevice>(this.detach_tblDevice));
			this._tblGroup = default(EntityRef<tblGroup>);
			OnCreated();
		}
		
		[Column(Storage="_GroupID", DbType="Int")]
		public System.Nullable<int> GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					if (this._tblGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[Column(Storage="_StationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this.OnStationIDChanging(value);
					this.SendPropertyChanging();
					this._StationID = value;
					this.SendPropertyChanged("StationID");
					this.OnStationIDChanged();
				}
			}
		}
		
		[Column(Storage="_Deleted", DbType="Bit")]
		public System.Nullable<bool> Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_Remark", DbType="NVarChar(1000)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[Column(Storage="_CommuniType", DbType="Int")]
		public System.Nullable<int> CommuniType
		{
			get
			{
				return this._CommuniType;
			}
			set
			{
				if ((this._CommuniType != value))
				{
					this.OnCommuniTypeChanging(value);
					this.SendPropertyChanging();
					this._CommuniType = value;
					this.SendPropertyChanged("CommuniType");
					this.OnCommuniTypeChanged();
				}
			}
		}
		
		[Column(Storage="_CommuniTypeContent", DbType="NVarChar(1000)")]
		public string CommuniTypeContent
		{
			get
			{
				return this._CommuniTypeContent;
			}
			set
			{
				if ((this._CommuniTypeContent != value))
				{
					this.OnCommuniTypeContentChanging(value);
					this.SendPropertyChanging();
					this._CommuniTypeContent = value;
					this.SendPropertyChanged("CommuniTypeContent");
					this.OnCommuniTypeContentChanged();
				}
			}
		}
		
		[Association(Name="tblStation_tblDevice", Storage="_tblDevice", OtherKey="StationID")]
		public EntitySet<tblDevice> tblDevice
		{
			get
			{
				return this._tblDevice;
			}
			set
			{
				this._tblDevice.Assign(value);
			}
		}
		
		[Association(Name="tblGroup_tblStation", Storage="_tblGroup", ThisKey="GroupID", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblGroup tblGroup
		{
			get
			{
				return this._tblGroup.Entity;
			}
			set
			{
				tblGroup previousValue = this._tblGroup.Entity;
				if (((previousValue != value) 
							|| (this._tblGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblGroup.Entity = null;
						previousValue.tblStation.Remove(this);
					}
					this._tblGroup.Entity = value;
					if ((value != null))
					{
						value.tblStation.Add(this);
						this._GroupID = value.GroupID;
					}
					else
					{
						this._GroupID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblGroup");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDevice(tblDevice entity)
		{
			this.SendPropertyChanging();
			entity.tblStation = this;
		}
		
		private void detach_tblDevice(tblDevice entity)
		{
			this.SendPropertyChanging();
			entity.tblStation = null;
		}
	}
	
	[Table(Name="dbo.tblGroup")]
	public partial class tblGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GroupID;
		
		private string _GroupName;
		
		private string _GroupLeader;
		
		private string _ContactWay;
		
		private string _Remark;
		
		private System.Nullable<bool> _Deleted;
		
		private EntitySet<tblStation> _tblStation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroupIDChanging(int value);
    partial void OnGroupIDChanged();
    partial void OnGroupNameChanging(string value);
    partial void OnGroupNameChanged();
    partial void OnGroupLeaderChanging(string value);
    partial void OnGroupLeaderChanged();
    partial void OnContactWayChanging(string value);
    partial void OnContactWayChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnDeletedChanging(System.Nullable<bool> value);
    partial void OnDeletedChanged();
    #endregion
		
		public tblGroup()
		{
			this._tblStation = new EntitySet<tblStation>(new Action<tblStation>(this.attach_tblStation), new Action<tblStation>(this.detach_tblStation));
			OnCreated();
		}
		
		[Column(Storage="_GroupID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[Column(Storage="_GroupName", DbType="NVarChar(50)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this.OnGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GroupName = value;
					this.SendPropertyChanged("GroupName");
					this.OnGroupNameChanged();
				}
			}
		}
		
		[Column(Storage="_GroupLeader", DbType="NVarChar(50)")]
		public string GroupLeader
		{
			get
			{
				return this._GroupLeader;
			}
			set
			{
				if ((this._GroupLeader != value))
				{
					this.OnGroupLeaderChanging(value);
					this.SendPropertyChanging();
					this._GroupLeader = value;
					this.SendPropertyChanged("GroupLeader");
					this.OnGroupLeaderChanged();
				}
			}
		}
		
		[Column(Storage="_ContactWay", DbType="NVarChar(50)")]
		public string ContactWay
		{
			get
			{
				return this._ContactWay;
			}
			set
			{
				if ((this._ContactWay != value))
				{
					this.OnContactWayChanging(value);
					this.SendPropertyChanging();
					this._ContactWay = value;
					this.SendPropertyChanged("ContactWay");
					this.OnContactWayChanged();
				}
			}
		}
		
		[Column(Storage="_Remark", DbType="NVarChar(100)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[Column(Storage="_Deleted", DbType="Bit")]
		public System.Nullable<bool> Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[Association(Name="tblGroup_tblStation", Storage="_tblStation", OtherKey="GroupID")]
		public EntitySet<tblStation> tblStation
		{
			get
			{
				return this._tblStation;
			}
			set
			{
				this._tblStation.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblStation(tblStation entity)
		{
			this.SendPropertyChanging();
			entity.tblGroup = this;
		}
		
		private void detach_tblStation(tblStation entity)
		{
			this.SendPropertyChanging();
			entity.tblGroup = null;
		}
	}
	
	[Table(Name="dbo.tblMeasureSluiceData")]
	public partial class tblMeasureSluiceData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MeasureSluiceDataID;
		
		private System.Nullable<int> _DeviceID;
		
		private System.Nullable<System.DateTime> _DT;
		
		private System.Nullable<float> _BeforeWL;
		
		private System.Nullable<float> _BehindWL;
		
		private System.Nullable<float> _InstantFlux;
		
		private System.Nullable<float> _Height;
		
		private System.Nullable<float> _RemainedAmount;
		
		private System.Nullable<float> _UsedAmount;
		
		private EntitySet<tblMeasureSluiceDataLast> _tblMeasureSluiceDataLast;
		
		private EntityRef<tblDevice> _tblDevice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMeasureSluiceDataIDChanging(int value);
    partial void OnMeasureSluiceDataIDChanged();
    partial void OnDeviceIDChanging(System.Nullable<int> value);
    partial void OnDeviceIDChanged();
    partial void OnDTChanging(System.Nullable<System.DateTime> value);
    partial void OnDTChanged();
    partial void OnBeforeWLChanging(System.Nullable<float> value);
    partial void OnBeforeWLChanged();
    partial void OnBehindWLChanging(System.Nullable<float> value);
    partial void OnBehindWLChanged();
    partial void OnInstantFluxChanging(System.Nullable<float> value);
    partial void OnInstantFluxChanged();
    partial void OnHeightChanging(System.Nullable<float> value);
    partial void OnHeightChanged();
    partial void OnRemainedAmountChanging(System.Nullable<float> value);
    partial void OnRemainedAmountChanged();
    partial void OnUsedAmountChanging(System.Nullable<float> value);
    partial void OnUsedAmountChanged();
    #endregion
		
		public tblMeasureSluiceData()
		{
			this._tblMeasureSluiceDataLast = new EntitySet<tblMeasureSluiceDataLast>(new Action<tblMeasureSluiceDataLast>(this.attach_tblMeasureSluiceDataLast), new Action<tblMeasureSluiceDataLast>(this.detach_tblMeasureSluiceDataLast));
			this._tblDevice = default(EntityRef<tblDevice>);
			OnCreated();
		}
		
		[Column(Storage="_MeasureSluiceDataID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MeasureSluiceDataID
		{
			get
			{
				return this._MeasureSluiceDataID;
			}
			set
			{
				if ((this._MeasureSluiceDataID != value))
				{
					this.OnMeasureSluiceDataIDChanging(value);
					this.SendPropertyChanging();
					this._MeasureSluiceDataID = value;
					this.SendPropertyChanged("MeasureSluiceDataID");
					this.OnMeasureSluiceDataIDChanged();
				}
			}
		}
		
		[Column(Storage="_DeviceID", DbType="Int")]
		public System.Nullable<int> DeviceID
		{
			get
			{
				return this._DeviceID;
			}
			set
			{
				if ((this._DeviceID != value))
				{
					if (this._tblDevice.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDeviceIDChanging(value);
					this.SendPropertyChanging();
					this._DeviceID = value;
					this.SendPropertyChanged("DeviceID");
					this.OnDeviceIDChanged();
				}
			}
		}
		
		[Column(Storage="_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT
		{
			get
			{
				return this._DT;
			}
			set
			{
				if ((this._DT != value))
				{
					this.OnDTChanging(value);
					this.SendPropertyChanging();
					this._DT = value;
					this.SendPropertyChanged("DT");
					this.OnDTChanged();
				}
			}
		}
		
		[Column(Storage="_BeforeWL", DbType="Real")]
		public System.Nullable<float> BeforeWL
		{
			get
			{
				return this._BeforeWL;
			}
			set
			{
				if ((this._BeforeWL != value))
				{
					this.OnBeforeWLChanging(value);
					this.SendPropertyChanging();
					this._BeforeWL = value;
					this.SendPropertyChanged("BeforeWL");
					this.OnBeforeWLChanged();
				}
			}
		}
		
		[Column(Storage="_BehindWL", DbType="Real")]
		public System.Nullable<float> BehindWL
		{
			get
			{
				return this._BehindWL;
			}
			set
			{
				if ((this._BehindWL != value))
				{
					this.OnBehindWLChanging(value);
					this.SendPropertyChanging();
					this._BehindWL = value;
					this.SendPropertyChanged("BehindWL");
					this.OnBehindWLChanged();
				}
			}
		}
		
		[Column(Storage="_InstantFlux", DbType="Real")]
		public System.Nullable<float> InstantFlux
		{
			get
			{
				return this._InstantFlux;
			}
			set
			{
				if ((this._InstantFlux != value))
				{
					this.OnInstantFluxChanging(value);
					this.SendPropertyChanging();
					this._InstantFlux = value;
					this.SendPropertyChanged("InstantFlux");
					this.OnInstantFluxChanged();
				}
			}
		}
		
		[Column(Storage="_Height", DbType="Real")]
		public System.Nullable<float> Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[Column(Storage="_RemainedAmount", DbType="Real")]
		public System.Nullable<float> RemainedAmount
		{
			get
			{
				return this._RemainedAmount;
			}
			set
			{
				if ((this._RemainedAmount != value))
				{
					this.OnRemainedAmountChanging(value);
					this.SendPropertyChanging();
					this._RemainedAmount = value;
					this.SendPropertyChanged("RemainedAmount");
					this.OnRemainedAmountChanged();
				}
			}
		}
		
		[Column(Storage="_UsedAmount", DbType="Real")]
		public System.Nullable<float> UsedAmount
		{
			get
			{
				return this._UsedAmount;
			}
			set
			{
				if ((this._UsedAmount != value))
				{
					this.OnUsedAmountChanging(value);
					this.SendPropertyChanging();
					this._UsedAmount = value;
					this.SendPropertyChanged("UsedAmount");
					this.OnUsedAmountChanged();
				}
			}
		}
		
		[Association(Name="tblMeasureSluiceData_tblMeasureSluiceDataLast", Storage="_tblMeasureSluiceDataLast", OtherKey="MeasureSluiceDataID")]
		public EntitySet<tblMeasureSluiceDataLast> tblMeasureSluiceDataLast
		{
			get
			{
				return this._tblMeasureSluiceDataLast;
			}
			set
			{
				this._tblMeasureSluiceDataLast.Assign(value);
			}
		}
		
		[Association(Name="tblDevice_tblMeasureSluiceData", Storage="_tblDevice", ThisKey="DeviceID", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblDevice tblDevice
		{
			get
			{
				return this._tblDevice.Entity;
			}
			set
			{
				tblDevice previousValue = this._tblDevice.Entity;
				if (((previousValue != value) 
							|| (this._tblDevice.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDevice.Entity = null;
						previousValue.tblMeasureSluiceData.Remove(this);
					}
					this._tblDevice.Entity = value;
					if ((value != null))
					{
						value.tblMeasureSluiceData.Add(this);
						this._DeviceID = value.DeviceID;
					}
					else
					{
						this._DeviceID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblDevice");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblMeasureSluiceDataLast(tblMeasureSluiceDataLast entity)
		{
			this.SendPropertyChanging();
			entity.tblMeasureSluiceData = this;
		}
		
		private void detach_tblMeasureSluiceDataLast(tblMeasureSluiceDataLast entity)
		{
			this.SendPropertyChanging();
			entity.tblMeasureSluiceData = null;
		}
	}
	
	[Table(Name="dbo.tblMeasureSluiceDataLast")]
	public partial class tblMeasureSluiceDataLast : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MeasureSluiceDataLastID;
		
		private System.Nullable<int> _MeasureSluiceDataID;
		
		private EntityRef<tblMeasureSluiceData> _tblMeasureSluiceData;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMeasureSluiceDataLastIDChanging(int value);
    partial void OnMeasureSluiceDataLastIDChanged();
    partial void OnMeasureSluiceDataIDChanging(System.Nullable<int> value);
    partial void OnMeasureSluiceDataIDChanged();
    #endregion
		
		public tblMeasureSluiceDataLast()
		{
			this._tblMeasureSluiceData = default(EntityRef<tblMeasureSluiceData>);
			OnCreated();
		}
		
		[Column(Storage="_MeasureSluiceDataLastID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MeasureSluiceDataLastID
		{
			get
			{
				return this._MeasureSluiceDataLastID;
			}
			set
			{
				if ((this._MeasureSluiceDataLastID != value))
				{
					this.OnMeasureSluiceDataLastIDChanging(value);
					this.SendPropertyChanging();
					this._MeasureSluiceDataLastID = value;
					this.SendPropertyChanged("MeasureSluiceDataLastID");
					this.OnMeasureSluiceDataLastIDChanged();
				}
			}
		}
		
		[Column(Storage="_MeasureSluiceDataID", DbType="Int")]
		public System.Nullable<int> MeasureSluiceDataID
		{
			get
			{
				return this._MeasureSluiceDataID;
			}
			set
			{
				if ((this._MeasureSluiceDataID != value))
				{
					if (this._tblMeasureSluiceData.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMeasureSluiceDataIDChanging(value);
					this.SendPropertyChanging();
					this._MeasureSluiceDataID = value;
					this.SendPropertyChanged("MeasureSluiceDataID");
					this.OnMeasureSluiceDataIDChanged();
				}
			}
		}
		
		[Association(Name="tblMeasureSluiceData_tblMeasureSluiceDataLast", Storage="_tblMeasureSluiceData", ThisKey="MeasureSluiceDataID", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblMeasureSluiceData tblMeasureSluiceData
		{
			get
			{
				return this._tblMeasureSluiceData.Entity;
			}
			set
			{
				tblMeasureSluiceData previousValue = this._tblMeasureSluiceData.Entity;
				if (((previousValue != value) 
							|| (this._tblMeasureSluiceData.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMeasureSluiceData.Entity = null;
						previousValue.tblMeasureSluiceDataLast.Remove(this);
					}
					this._tblMeasureSluiceData.Entity = value;
					if ((value != null))
					{
						value.tblMeasureSluiceDataLast.Add(this);
						this._MeasureSluiceDataID = value.MeasureSluiceDataID;
					}
					else
					{
						this._MeasureSluiceDataID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblMeasureSluiceData");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.vMeasureSluiceData")]
	public partial class vMeasureSluiceData
	{
		
		private int _GroupID;
		
		private int _StationID;
		
		private int _DeviceID;
		
		private string _GroupName;
		
		private string _StationName;
		
		private int _MeasureSluiceDataID;
		
		private System.Nullable<System.DateTime> _DT;
		
		private System.Nullable<float> _BeforeWL;
		
		private System.Nullable<float> _BehindWL;
		
		private System.Nullable<float> _InstantFlux;
		
		private System.Nullable<float> _Height;
		
		private System.Nullable<float> _RemainedAmount;
		
		private System.Nullable<float> _UsedAmount;
		
		public vMeasureSluiceData()
		{
		}
		
		[Column(Storage="_GroupID", DbType="Int NOT NULL")]
		public int GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this._GroupID = value;
				}
			}
		}
		
		[Column(Storage="_StationID", DbType="Int NOT NULL")]
		public int StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this._StationID = value;
				}
			}
		}
		
		[Column(Storage="_DeviceID", DbType="Int NOT NULL")]
		public int DeviceID
		{
			get
			{
				return this._DeviceID;
			}
			set
			{
				if ((this._DeviceID != value))
				{
					this._DeviceID = value;
				}
			}
		}
		
		[Column(Storage="_GroupName", DbType="NVarChar(50)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this._GroupName = value;
				}
			}
		}
		
		[Column(Storage="_StationName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string StationName
		{
			get
			{
				return this._StationName;
			}
			set
			{
				if ((this._StationName != value))
				{
					this._StationName = value;
				}
			}
		}
		
		[Column(Storage="_MeasureSluiceDataID", DbType="Int NOT NULL")]
		public int MeasureSluiceDataID
		{
			get
			{
				return this._MeasureSluiceDataID;
			}
			set
			{
				if ((this._MeasureSluiceDataID != value))
				{
					this._MeasureSluiceDataID = value;
				}
			}
		}
		
		[Column(Storage="_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT
		{
			get
			{
				return this._DT;
			}
			set
			{
				if ((this._DT != value))
				{
					this._DT = value;
				}
			}
		}
		
		[Column(Storage="_BeforeWL", DbType="Real")]
		public System.Nullable<float> BeforeWL
		{
			get
			{
				return this._BeforeWL;
			}
			set
			{
				if ((this._BeforeWL != value))
				{
					this._BeforeWL = value;
				}
			}
		}
		
		[Column(Storage="_BehindWL", DbType="Real")]
		public System.Nullable<float> BehindWL
		{
			get
			{
				return this._BehindWL;
			}
			set
			{
				if ((this._BehindWL != value))
				{
					this._BehindWL = value;
				}
			}
		}
		
		[Column(Storage="_InstantFlux", DbType="Real")]
		public System.Nullable<float> InstantFlux
		{
			get
			{
				return this._InstantFlux;
			}
			set
			{
				if ((this._InstantFlux != value))
				{
					this._InstantFlux = value;
				}
			}
		}
		
		[Column(Storage="_Height", DbType="Real")]
		public System.Nullable<float> Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this._Height = value;
				}
			}
		}
		
		[Column(Storage="_RemainedAmount", DbType="Real")]
		public System.Nullable<float> RemainedAmount
		{
			get
			{
				return this._RemainedAmount;
			}
			set
			{
				if ((this._RemainedAmount != value))
				{
					this._RemainedAmount = value;
				}
			}
		}
		
		[Column(Storage="_UsedAmount", DbType="Real")]
		public System.Nullable<float> UsedAmount
		{
			get
			{
				return this._UsedAmount;
			}
			set
			{
				if ((this._UsedAmount != value))
				{
					this._UsedAmount = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.vMeasureSluiceDataLast")]
	public partial class vMeasureSluiceDataLast
	{
		
		private int _GroupID;
		
		private int _StationID;
		
		private int _DeviceID;
		
		private string _GroupName;
		
		private string _StationName;
		
		private int _MeasureSluiceDataID;
		
		private System.Nullable<System.DateTime> _DT;
		
		private System.Nullable<float> _BeforeWL;
		
		private System.Nullable<float> _BehindWL;
		
		private System.Nullable<float> _InstantFlux;
		
		private System.Nullable<float> _Height;
		
		private System.Nullable<float> _RemainedAmount;
		
		private System.Nullable<float> _UsedAmount;
		
		public vMeasureSluiceDataLast()
		{
		}
		
		[Column(Storage="_GroupID", DbType="Int NOT NULL")]
		public int GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this._GroupID = value;
				}
			}
		}
		
		[Column(Storage="_StationID", DbType="Int NOT NULL")]
		public int StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this._StationID = value;
				}
			}
		}
		
		[Column(Storage="_DeviceID", DbType="Int NOT NULL")]
		public int DeviceID
		{
			get
			{
				return this._DeviceID;
			}
			set
			{
				if ((this._DeviceID != value))
				{
					this._DeviceID = value;
				}
			}
		}
		
		[Column(Storage="_GroupName", DbType="NVarChar(50)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this._GroupName = value;
				}
			}
		}
		
		[Column(Storage="_StationName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string StationName
		{
			get
			{
				return this._StationName;
			}
			set
			{
				if ((this._StationName != value))
				{
					this._StationName = value;
				}
			}
		}
		
		[Column(Storage="_MeasureSluiceDataID", DbType="Int NOT NULL")]
		public int MeasureSluiceDataID
		{
			get
			{
				return this._MeasureSluiceDataID;
			}
			set
			{
				if ((this._MeasureSluiceDataID != value))
				{
					this._MeasureSluiceDataID = value;
				}
			}
		}
		
		[Column(Storage="_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT
		{
			get
			{
				return this._DT;
			}
			set
			{
				if ((this._DT != value))
				{
					this._DT = value;
				}
			}
		}
		
		[Column(Storage="_BeforeWL", DbType="Real")]
		public System.Nullable<float> BeforeWL
		{
			get
			{
				return this._BeforeWL;
			}
			set
			{
				if ((this._BeforeWL != value))
				{
					this._BeforeWL = value;
				}
			}
		}
		
		[Column(Storage="_BehindWL", DbType="Real")]
		public System.Nullable<float> BehindWL
		{
			get
			{
				return this._BehindWL;
			}
			set
			{
				if ((this._BehindWL != value))
				{
					this._BehindWL = value;
				}
			}
		}
		
		[Column(Storage="_InstantFlux", DbType="Real")]
		public System.Nullable<float> InstantFlux
		{
			get
			{
				return this._InstantFlux;
			}
			set
			{
				if ((this._InstantFlux != value))
				{
					this._InstantFlux = value;
				}
			}
		}
		
		[Column(Storage="_Height", DbType="Real")]
		public System.Nullable<float> Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this._Height = value;
				}
			}
		}
		
		[Column(Storage="_RemainedAmount", DbType="Real")]
		public System.Nullable<float> RemainedAmount
		{
			get
			{
				return this._RemainedAmount;
			}
			set
			{
				if ((this._RemainedAmount != value))
				{
					this._RemainedAmount = value;
				}
			}
		}
		
		[Column(Storage="_UsedAmount", DbType="Real")]
		public System.Nullable<float> UsedAmount
		{
			get
			{
				return this._UsedAmount;
			}
			set
			{
				if ((this._UsedAmount != value))
				{
					this._UsedAmount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
